This notebook works with dicoms.  Tries to match two dicoms together and plot them

### Imports

In [15]:
import os
import pydicom
import numpy as np
import pandas as pd
from Dicom import Dicom # Custom dicom class

from glob import glob
from os.path import join
from tqdm import tqdm_notebook as tqdm

### Settings

In [16]:
dicom_dir = "/Volumes/group/PANLab_Datasets/ENGAGE_2/raw/000_data_archive/ENG000018/go_no_go_2/dicoms"

### Helpers

In [17]:
for dicom_path in glob(join(dicom_dir, "*")):
    dicom = Dicom(dicom_path)
    data = dicom.data


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


RuntimeError: No active exception to reraise